package d20staticblock_instanceblock_oop;

public class AnimalRunner {
    public static void main(String[] args) {
        Dog d = new Dog();
        d.bark();//Dogs bark....
        d.feedWithMilk();//Mammals feed their babies with milk...
        d.drink();//Anımals drınk....
        d.eat();//Animals eat....

        Bird b =new Bird();
        b.tweet() ; //Birds tweet...
        b.eat(); // Animals eat ...
        b.drink();//Anımals drınk....




    }
}
